# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
  connect_to:
    host: 192.168.1.1
    port: 8080
  client:
    host: 192.168.1.3
    port: 50123
server:
  bind:
    host: 192.168.1.1
    port: 8080
  client:
    host: 192.168.1.2
    port: 50123
catnip:
  my_ipv4_addr: 192.168.1.2
  my_link_addr: "9c:dc:71:56:bf:25"
  my_interface_name: "ens1f1np1"
  arp_table:
    "9c:dc:71:4b:83:61": "192.168.1.1"
    "9c:dc:71:56:bf:25": "192.168.1.3"
dpdk:
  eal_init: ["", "-c", "0xff", "-n", "4", "-a", "03:00.1","--proc-type=auto"]
catnap:
  tcp_keepalive:
    enabled: false
    time_millis: 0
    interval: 0
  linger:
    enabled: true
    time_seconds: 0

# vim: set tabstop=2 shiftwidth=2
